Algoritmo "10 ler dois números quaisquer, dividir o primeiro pelo segundo "
//FUA para ler dois números quaisquer, dividir o primeiro pelo segundo.
//Mostrar os números lidos e o resultado calculado.
Var
   A, B, resultado: real
Inicio
      Escreva("Digite um número: ")
      leia(A)
      Escreva("Digite outro número: ")
      leia(B)
      resultado <- (A/B)
      Escreva("A divisão de", A," /", B," é: ", resultado)

Fimalgoritmo