Algoritmo "18 calcular a média de quatro números inteiros"
//FUA para calcular a média de quatro números inteiros e exibir o resultado
//final.
Var
   A, B, C, D: inteiro
   MD: real
Inicio
      Escreva("Digite um número: ")
      leia(A)
      Escreva("Digite um segundo número: ")
      leia(B)
      Escreva("Digite um terceiro número: ")
      leia(C)
      Escreva("Digite um quarto número: ")
      leia(D)
      MD<- (A+B+C+D)/4
      Escreva("A média dos números é: ", MD)

Fimalgoritmo