Algoritmo "5 calcular a área de um triângulo, exibindo o resultado final."
//FUA para calcular a área de um triângulo, exibindo o resultado final.
//A base e a altura são dados que devem ser lidos como entrada.
Var
   base, altura, area: real
   
Inicio
      Escreva("Digite o valor da base: ")
      leia(base)
      Escreva("Digite o valor da altura: ")
      leia(altura)
      area <- (base*altura)/2
      Escreva("A área do triângulo é: ", area)

Fimalgoritmo