Algoritmo "9 ler dois numeros quaisquer, e calcular a soma deles"
//FUA para ler dois números quaisquer, calcular a soma deles e após mostrar os
//números lidos e o resultado da soma.
Var
   A, B, resultado: real

Inicio
      Escreva("Digite um número: ")
      leia (A)
      Escreva("Digite outro número: ")
      leia (B)
      resultado <- (A+B)
      Escreva("A soma de", A, " +", B, " é igual a", resultado)

      
Fimalgoritmo